import { ICPData } from '../types';

/**
 * Generate markdown content from ICP data
 */
export function generateICPMarkdown(data: ICPData): string {
  return `# Ideal Customer Profile (ICP)
Generated by ICP Builder AI

## Firmographics
- **Role/Persona**: ${data.role || 'N/A'}
- **Industry**: ${data.industry || 'N/A'}
- **Company Size**: ${data.companySize || 'N/A'}
- **Geography**: ${data.geography || 'N/A'}

## Psychographics
### Pain Points
${data.painPoints.map(p => `- ${p}`).join('\n') || 'N/A'}

### Goals
${data.goals.map(g => `- ${g}`).join('\n') || 'N/A'}

## Strategy
### Purchase Triggers
${data.purchaseTriggers.map(t => `- ${t}`).join('\n') || 'N/A'}

### Common Objections
${data.objections.map(o => `- ${o}`).join('\n') || 'N/A'}

## Technology
### Tech Stack
${data.techStack.map(t => `- ${t}`).join('\n') || 'N/A'}

---
Built with ICP Builder AI`;
}

/**
 * Copy text to clipboard
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(text);
      return true;
    } else {
      // Fallback for older browsers
      const textArea = document.createElement('textarea');
      textArea.value = text;
      textArea.style.position = 'fixed';
      textArea.style.left = '-999999px';
      textArea.style.top = '-999999px';
      document.body.appendChild(textArea);
      textArea.focus();
      textArea.select();
      const result = document.execCommand('copy');
      textArea.remove();
      return result;
    }
  } catch (error) {
    console.error('Failed to copy:', error);
    return false;
  }
}

/**
 * Share using Web Share API or fallback to clipboard
 */
export async function shareICP(data: ICPData): Promise<{ success: boolean; method: 'share' | 'clipboard' | 'none' }> {
  const content = generateICPMarkdown(data);

  // Try Web Share API first (mobile)
  if (navigator.share) {
    try {
      await navigator.share({
        title: 'My Ideal Customer Profile',
        text: content
      });
      return { success: true, method: 'share' };
    } catch (error) {
      // User cancelled or error occurred
      if ((error as Error).name !== 'AbortError') {
        console.error('Share failed:', error);
      }
    }
  }

  // Fallback to clipboard
  const copied = await copyToClipboard(content);
  return { success: copied, method: copied ? 'clipboard' : 'none' };
}

/**
 * Download ICP as markdown file
 */
export function downloadICP(data: ICPData): void {
  const content = generateICPMarkdown(data);
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `ICP-${data.role.replace(/\s+/g, '-') || 'Draft'}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
